---
sudo: required

# whitelist
branches:
  only:
    - master
    - develop

services:
  - docker

before_install:
  - "git clone https://github.com/sstephenson/bats.git"
  - "mkdir -p bin && cd bats && ./install.sh ../bin & cd ../"
  - "export HOME_DIR=$PWD"
  - "sudo docker pull voronenko/vault"
  - "export ROOT_TOKEN=abfd0e04-7922-6850-e1bd-f02c325f1e2c"
  - "docker run -d -p 8200:8200 --hostname vault --name vault voronenko/vault"
  - "echo ROOT_TOKEN - $ROOT_TOKEN"
  - "export VAULT_ADDR=http://$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' vault):8200"
  - "echo VAULT_ADDR - $VAULT_ADDR"
  - "wget https://releases.hashicorp.com/vault/0.6.0/vault_0.6.0_linux_amd64.zip"
  - "unzip -d $HOME_DIR/tests $HOME_DIR/vault_0.6.0_linux_amd64.zip && rm $HOME_DIR/vault_0.6.0_linux_amd64.zip && chmod 755 $HOME_DIR/tests/vault"
  - "alias vault=$HOME_DIR/tests/vault"
script:
  # execute tests
  - "export PATH=$HOME_DIR:$PWD/bin/bin:$PATH"  
  - '$HOME_DIR/tests/vault.bats'

  # Clean up
  - sudo docker stop "vault"
  - sudo docker rm "vault"
